export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const FETCH_JOBS_START = 'FETCH_JOBS_START';
export const FETCH_JOBS_SUCCESS = 'FETCH_ALL_JOBS';
export const FETCH_JOB = 'FETCH_JOB';
export const ADD_JOB = 'ADD_JOB';
export const DELETE_JOB = 'DELETE_JOB';

export const ADD_JOB_TO_USER = 'ADD_JOB_TO_USER';
export const FETCH_USERS_JOBS_START = 'FETCH_USERS_JOBS_START';
export const FETCH_USERS_JOBS_SUCCESS = 'FETCH_USERS_JOBS_SUCCESS';
export const FETCH_USERS_JOBS_BY_JOBID = 'FETCH_USERS_JOBS_BY_JOBID';
export const FETCH_USERS_JOBS_BY_USERID = 'FETCH_USERS_JOBS_BY_USERID';

export const GET_PROFILE = 'GET_PROFILE';
export const GET_PROFILES = 'GET_PROFILES';
export const PROFILE_LOADING = 'PROFILE_LOADING';
export const CLEAR_CURRENT_PROFILE = 'CLEAR_CURRENT_PROFILE';